# Q1

In [1]:
import numpy as np
array = np.arange(2, 50, 3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Q2

In [16]:
import numpy as np
arr1 = np.empty(5)
arr2 = np.empty(5)
for i in range(5):
    arr1[i]=int(input())
for i in range(5):
    arr2[i]=int(input())
print(np.concatenate([arr1,arr2]))
print(np.sort(arr1))
print(np.sort(arr2))
print(np.sort(np.concatenate([arr1,arr2])))

3
2
1
5
4
8
7
6
9
0
[3. 2. 1. 5. 4. 8. 7. 6. 9. 0.]
[1. 2. 3. 4. 5.]
[0. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# Q3

In [12]:
import numpy as np
Arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5],
                 [5, 7, 10] ] )
print(Arr.ndim)
print(Arr.size)

2
9


# Q4

In [15]:
import numpy as np
arr = np.array([1, 2, 4, 5, 7, 8, 10, 12])
print(arr.ndim)
newarr = arr.reshape(2, 4)
print(newarr.ndim)

1
2
